Adding stronger types to Cotter interfaces
cotterapp/cotter-js pull request #5
Opened 2020-08-07 02:22 UTC by theFong

Im not sure how the Cotter.d.ts is generated but I have added stronger types in hopes of strengthening the interface.

2020-08-07 03:34 UTC, theFong commented
I would like to add stronger types to the `verificationProccessPromise` but looks like an interface for the verifySuccess payload has not been defined yet?

2020-08-07 03:50 UTC, theFong commented
I added a payload interface to type `verificationProccessPromise` resolution. Probably could be used in more publicly exposed areas. Let me know if you would like the naming changed etc or want it moved somewhere else :)

2020-08-07 03:54 UTC, theFong commented on src/API.ts
> +  ): Promise<Payload> {
Assuming this is the same interface

2020-08-07 03:54 UTC, theFong commented on src/API.ts
> +  ): Promise<Payload> {
Assuming this is the same interface

2020-08-07 04:02 UTC, putrikarunia commented
Hey, thank you for contributing! I think verifySuccess is supposed to be the response that is returned to the client because it was used for `resolve(self.verifySuccess)`. Is it different when you tried it? 

It should be like this:

```typescript
export interface VerifySuccess {
  email?: String;
  phone?: String;
  oauth_token: OAuthToken;
  user: User;
  identifier?: String; // only from WebAuthn same as email/phone
  status?: String; // only from WebAuthn = SUCCESS or CANCELED
}
```
where `OAuthToken` is from `handler/TokenHandler.ts` but missing some parts:
```diff

export interface OAuthToken {
  access_token: string;
  id_token: string;
  token_type: string;
  refresh_token: string;
+  expires_in: number;
+  auth_method: string;
}
```
and `User` from `models/User`.

2020-08-07 04:20 UTC, theFong commented
> Hey, thank you for contributing! I think verifySuccess is supposed to be the response that is returned to the client because it was used for `resolve(self.verifySuccess)`. Is it different when you tried it?
> 
> It should be like this:
> 
> ```ts
> export interface VerifySuccess {
>   email?: String;
>   phone?: String;
>   oauth_token: OAuthToken;
>   user: User;
>   identifier?: String; // only from WebAuthn same as email/phone
>   status?: String; // only from WebAuthn = SUCCESS or CANCELED
> }
> ```
> 
> where `OAuthToken` is from `handler/TokenHandler.ts` but missing some parts:
> 
> ```diff
> export interface OAuthToken {
>   access_token: string;
>   id_token: string;
>   token_type: string;
>   refresh_token: string;
> +  expires_in: number;
> +  auth_method: string;
> }
> ```
> 
> and `User` from `models/User`.

Oops! You are totally correct the payload interface was something I was logging in the onBegin and not on the verifySuccess. I have added those accordingly.
Added the VerifySuccess interface to binder.ts. Is this the proper file to use?

2020-08-08 01:01 UTC, putrikarunia requested changes
Looks good 👍, just need to update the `Payload` to the one I posted in the comment.

2020-08-08 01:01 UTC, putrikarunia commented on src/binder.ts
> +}
the Payload that is passed into `OnBegin` should be like this
```typescript
export interface Payload {
  auth_required: boolean;
  device_name: string; // User Agent
  device_type: "BROWSER";
  identifier: string; // User's email/phone
  identifier_type: "EMAIL" | "PHONE";
}
```
What you're seeing above (challenge, challenge_id, etc) is probably from some other console log which I should remove from the code.

2020-08-08 02:47 UTC, theFong commented
Changed Payload to reflect real object and changed name from `Payload` to `OnBeginPayload`

2020-08-09 04:45 UTC, putrikarunia approved these changes

2020-08-11 00:41 UTC, merged